apiVersion: v2
name: novu
description: A Helm chart for Kubernetes novu
type: application
icon: "http://tools.png"
version: "1.0.12"
appVersion: "1.0.12"
dependencies: []
  # - name: "redis"
  #   version: "20.2.1"
  #   repository: "oci://registry-1.docker.io/bitnamicharts"
  #   condition: redis.enabled
  # - name: "community-operator"
  #   version: "0.11.0"
  #   repository: "https://mongodb.github.io/helm-charts"
  #   condition: community-operator.enabled



    
