{{- if .Values.web.enabled }}
{{- if .Values.web.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "novu-chart.web.serviceAccountName" . }}
  labels:
    {{- include "novu-chart.labels" . | nindent 4 }}
  {{- with .Values.web.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.web.serviceAccount.automount }}
{{- end }}
{{- end }}
