{{- if .Values.web.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "novu.web.fullname" . }}
  labels:
    {{- include "novu.web.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: TCP
      name: http
  selector:
     {{- include "novu.web.selectorLabels" . | nindent 4 }}
{{- end }}