{{- range .Values.clusterissuer.clusters }}

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
spec:
  acme:
    server: {{ .server }}
    email: {{ .email }}
    privateKeySecretRef:
      name: {{ .privateKeySecretName }}
    solvers:
      - http01:
          ingress:
            class: {{ .ingressClass }}
{{- end }}