{{- if .Values.ws.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "novu.ws.fullname" . }}
  labels:
    {{- include "novu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ws.service.type }}
  ports:
    - port: {{ .Values.ws.service.port }}
      targetPort: {{ .Values.ws.service.targetPort }}
      protocol: TCP
      name: http
  selector:
     {{- include "novu.selectorLabels" . | nindent 4 }}
{{- end }}
