{{- if .Values.ws.enabled }}
{{- if .Values.ws.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "novu-chart.ws.serviceAccountName" . }}
  labels:
    {{- include "novu-chart.labels" . | nindent 4 }}
  {{- with .Values.ws.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.ws.serviceAccount.automount }}
{{- end }}
{{- end }}
