{{- if .Values.api.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "novu.api.fullname" . }}
  labels:
    {{- include "novu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
     {{- include "novu.selectorLabels" . | nindent 4 }}
{{- end }}