{{- if .Values.widget.enabled }}

{{- if .Values.widget.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "novu.widget.serviceAccountName" . }}
  labels:
    {{- include "novu.labels" . | nindent 4 }}
  {{- with .Values.widget.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.widget.serviceAccount.automount }}
{{- end }}
{{- end }}